---
kind: pipeline
type: docker
name: ansible-runner

globals:
  - &docker_creds
    username:
      from_secret: GIT_USER
    password:
      from_secret: GIT_PASSWORD

steps:
  - name: prepare-cache
    image: busybox
    commands:
      - mkdir -p /cache/${DRONE_REPO}/docker
    volumes:
      - name: cache
        path: /cache

  - name: build and publish
    image: plugins/docker
    privileged: true
    environment:
      GIT_USER:
        from_secret: GIT_USER
      GIT_PASSWORD:
        from_secret: GIT_PASSWORD
    settings:
      <<: *docker_creds
      repo: git.sbbh.cloud/sysadm/ansible-runner
      registry: git.sbbh.cloud
      mtu: 1450
      build_args_from_env:
        - GIT_USER
        - GIT_PASSWORD
      tags:
        - latest
    volumes:
      - name: docker
        path: /var/lib/docker
    when:
      event:
        - push
        - pull_request

  - name: build and publish (scheduled)
    image: plugins/docker
    privileged: true
    settings:
      <<: *docker_creds
      repo: git.sbbh.cloud/sysadm/ansible-runner
      registry: git.sbbh.cloud
      mtu: 1450
      pull_image: true
      no_cache: true
      tags:
        - latest
    when:
      event:
        - cron

  - name: discord notification
    image: appleboy/drone-discord
    settings:
      username: Drone
      webhook_id:
        from_secret: DISCORD_ID
      webhook_token:
        from_secret: DISCORD_TOKEN
      message: >
        {{#success build.status}}✅{{else}}⚠️{{/success}}
        repo: `[{{repo.name}}/{{commit.branch}}]` `[{{uppercase build.event}}]` [[#{{build.number}}]({{build.link}})][[{{truncate commit.sha 5}}]({{commit.link}})]
               commit: `{{commit.message}}`
    when:
      status: [success, failure, changed]
      event: [push]

volumes:
  - name: cache
    host:
      path: /var/cache
  - name: docker
    host:
      path: /var/cache/${DRONE_REPO}/docker

---
kind: secret
name: GIT_USER
get:
  path: doppler-drone
  name: GITEA_USER

---
kind: secret
name: GIT_PASSWORD
get:
  path: doppler-drone
  name: GITEA_PASSWORD

---
kind: secret
name: DISCORD_ID
get:
  path: doppler-drone
  name: DISCORD_ID

---
kind: secret
name: DISCORD_TOKEN
get:
  path: doppler-drone
  name: DISCORD_TOKEN
