---

kind: pipeline
type: docker
name: ansible-runner

globals:
  - &docker_creds
    username:
      from_secret: GITEA_USER
    password:
      from_secret: GITEA_PASSWORD

steps:
  - name: prepare-cache
    image: busybox
    commands:
      - mkdir -p /cache/${DRONE_REPO}/docker
    volumes:
      - name: cache
        path: /cache

  - name: build and publish
    image: plugins/docker
    privileged: true
    settings:
      repo: git.sbbh.cloud/sysadm/ansible-runner
      registry: git.sbbh.cloud
      mtu: 1450
      <<: *docker_creds
      tags:
        - latest
    volumes:
      - name: docker
        path: /var/lib/docker       
    when:
      event:
        - push
        - pull_request

  - name: build and publish (scheduled)
    image: plugins/docker
    privileged: true
    settings:
      repo: git.sbbh.cloud/sysadm/ansible-runner
      registry: git.sbbh.cloud
      mtu: 1450
      pull_image: true
      no_cache: true
      <<: *docker_creds
      tags:
        - latest
    when:
      event:
      - cron

volumes:
  - name: cache
    host:
      path: /var/cache
  - name: docker
    host:
      path: /var/cache/${DRONE_REPO}/docker

---

kind: secret
name: GITEA_USER
get:
  path: drone-doppler-secret
  name: GITEA_USER

---
kind: secret
name: GITEA_PASSWORD
get:
  path: drone-doppler-secret
  name: GITEA_PASSWORD
