---
kind: pipeline
type: docker
name: ansible-runner

trigger:
  branch:
    - main
  event:
    - cron
    - custom
    - rollback

globals:
  - &docker_creds
    username:
      from_secret: GITEA_USER
    password:
      from_secret: GITEA_PASSWORD

image_pull_secrets:
  - DOCKER_CONFIG

steps:
  - name: prepare-cache
    image: busybox
    commands:
      - mkdir -p /cache/${DRONE_REPO}/docker
    volumes:
      - name: cache
        path: /cache

  - name: build and publish
    image: plugins/docker
    privileged: true
    environment:
      GIT_USER:
        from_secret: GITEA_USER
      GIT_PASSWORD:
        from_secret: GITEA_PASSWORD
    settings:
      <<: *docker_creds
      repo: git.sbbh.cloud/infra/ansible-runner
      registry: git.sbbh.cloud
      mtu: 1450
      auto_tag: true
      build_args_from_env:
        - GIT_USER
        - GIT_PASSWORD
    volumes:
      - name: docker
        path: /var/lib/docker
    when:
      status: [success]
      event: [custom]

  - name: build and publish (cron)
    image: plugins/docker
    privileged: true
    environment:
      GIT_USER:
        from_secret: GITEA_USER
      GIT_PASSWORD:
        from_secret: GITEA_PASSWORD
    settings:
      <<: *docker_creds
      repo: git.sbbh.cloud/infra/ansible-runner
      registry: git.sbbh.cloud
      mtu: 1450
      pull_image: true
      no_cache: true
      auto_tag: true
      build_args_from_env:
        - GIT_USER
        - GIT_PASSWORD
    volumes:
      - name: docker
        path: /var/lib/docker
    when:
      status: [success]
      event: [cron]

  - name: discord notification
    image: appleboy/drone-discord
    settings:
      username: Drone
      webhook_id:
        from_secret: DISCORD_ID
      webhook_token:
        from_secret: DISCORD_TOKEN
      message: >
        {{#success build.status}}✅{{else}}⚠️{{/success}}
        repo: `[{{repo.name}}/{{commit.branch}}]` `[{{uppercase build.event}}]` [[#{{build.number}}]({{build.link}})][[{{truncate commit.sha 5}}]({{commit.link}})]
               commit: `{{commit.message}}`

volumes:
  - name: cache
    host:
      path: /var/cache/${DRONE_REPO}/docker

---
kind: secret
name: DOCKER_CONFIG
get:
  path: drone-secret
  name: DOCKER_CONFIG
---
kind: secret
name: GITEA_USER
get:
  path: drone-secret
  name: GITEA_USER
---
kind: secret
name: GITEA_PASSWORD
get:
  path: drone-secret
  name: GITEA_PASSWORD
---
kind: secret
name: DISCORD_ID
get:
  path: drone-secret
  name: DISCORD_ID
---
kind: secret
name: DISCORD_TOKEN
get:
  path: drone-secret
  name: DISCORD_TOKEN
