---

kind: pipeline
type: docker
name: ansible-runner

steps:
  - name: build and publish
    image: plugins/docker
    privileged: true
    settings:
      repo: git.sbbh.cloud/sysadm/ansible-runner
      registry: git.sbbh.cloud
      mtu: 1450
      username: 
        from_secret: GITEA_USER
      password: 
        from_secret: GITEA_PASSWORD
      tags:
        - latest
    when:
      event:
        - push
        - pull_request

  - name: build and publish (scheduled)
    image: plugins/docker
    privileged: true
    settings:
      repo: sysadm/ansible-runner
      registry: git.sbbh.cloud
      mtu: 1450
      pull_image: true
      no_cache: true
      username: 
        from_secret: GITEA_USER
      password: 
        from_secret: GITEA_PASSWORD
      tags:
        - latest
    when:
      event:
      - cron
---
kind: secret
name: DOCKER_USER
get:
  path: drone-doppler-secret
  name: DOCKER_USER
---
kind: secret
name: DOCKER_PASSWORD
get:
  path: drone-doppler-secret
  name: DOCKER_PASSWORD
---
kind: secret
name: GITEA_USER
get:
  path: drone-doppler-secret
  name: GITEA_USER
---
kind: secret
name: GITEA_PASSWORD
get:
  path: drone-doppler-secret
  name: GITEA_PASSWORD
